/* ===================================================================
 * Dreoarcana Arcana — the rules pages
 *
 * The rules, readable inside Foundry. Every table is rendered from
 * rules.js when it is shown, so the pages can never disagree with what
 * the builder does. The Arcanum's Rules tab shows them directly; the GM
 * can also publish them as a journal. Pages 1–8 are the Spell Builder
 * and Node Catalogue; pages 9–10 are the house procedure on the table.
 * =================================================================== */

import { SYSTEM_ID } from "./core.js";
import { INTENTS, CONVERSIONS, FORMS, RANGES, SIZES, EFFECTS, DISCIPLINES, UTILITY_NODES,
         DAMAGE_TYPES, TIERS, TIER_DIFFICULTY, DIFFICULTY_GRADES, OUTCOMES, FOCUS_PRESETS,
         CATALYST_PRESETS, COMPOUND_COMPLEXITY_BONUS, CIRCUMSTANCES } from "./rules.js";
import { setting, SETTINGS } from "./settings.js";
import { e } from "./html.js";

export const RULES_TITLE = "Arcana — Spell Builder";
const FOLDER = "Dreoarcana";

const table = (head, rows) =>
  `<table><thead><tr>${head.map(h => `<th>${h}</th>`).join("")}</tr></thead><tbody>${
    rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>`;

function pageFormulas() {
  return `
    <p>There are five important formulas for the spell casting.</p>
    ${table(["Formula", "Equation"], [
      ["Heat Formula", "H = Œ<sup>1.3</sup> × Complexity ÷ 6"],
      ["First Principle", "Œ = ξ × 1 ÷ (F × S)"],
      ["Second Principle", "Œ = ξ × 1 ÷ (F × S) × C"],
      ["Casting Time", "T<sub>cast</sub> = 4 s + Σ(C<sub>mods</sub>) × Γ"],
      ["Might Formula", "M = ξ"]
    ])}
    <h3>Variables</h3>
    ${table(["Symbol", "Name", "Description"], [
      ["ξ", "Converted Energy", "Energy the spell produces based on node selection (damage, healing, utility). Determined by the node ξ multipliers on the Power invested."],
      ["Complexity", "Spell Complexity", "Sum of all node complexity values. Used for Heat and Casting Time."],
      ["F", "Focus", "Reflects caster's mental strain or divided attention."],
      ["S", "Skill", "Caster's mastery over ξ flow. Higher S → more efficient conversion."],
      ["Œ", "Orie (raw energy)", "Calculated from ξ using intrinsic caster factors. Core Principle output before catalysts."],
      ["Γ", "Catalyst Quality", "Efficiency of external tools/conduits. Multiplies Œ_base; optional post-conversion modifier."],
      ["Œ_final", "Orie (final)", "Raw energy required after applying catalyst. Feeds Heat, Casting Time and dice."],
      ["H", "Heat", "Magical strain generated by spell. Depends on Œ_final and Complexity."],
      ["T_cast", "Casting Time", "Base 4 s + complexity modifiers."],
      ["Stored Orie", "—", "Reduces required Œ to produce the same ξ. Automatically reduces Heat."]
    ])}
    <h3>How the table reads them</h3>
    <ul>
      <li><strong>Power (N)</strong> is the ξ the caster puts in; every node multiplies it. ξ = N × Π(node ξ).</li>
      <li><strong>Skill S</strong> comes from the Mythras percentage: S = skill% ÷ ${setting(SETTINGS.skillDivisor) ?? 50}.</li>
      <li><strong>Focus F</strong> is an efficiency between 0 and 1 — full attention is 1, distraction lowers it and so raises Œ. The source says F &gt; 1 "reduces efficiency" while dividing by it; this keeps the formula literal and the intent intact.</li>
      <li><strong>Catalyst Γ</strong> multiplies Œ (Second Principle) and the complexity term of casting time. 1.0 is bare hands; a better catalyst is lower.</li>
      <li><strong>Stored Orie</strong> drawn for a cast is subtracted from Œ_final before conversion. Only what is converted heats: H uses Œ_final − drawn.</li>
      <li><strong>Might</strong> is shared evenly between a spell's effects for their magnitude; cost and Heat are paid on the whole.</li>
    </ul>`;
}

function pageIntents() {
  return `<p>Intent is priced by kindness: helping is cheaper than harming, and making something from nothing is the most expensive thing you can do.</p>
    ${table(["Name", "Short description", "ξ drain", "Complexity"],
      Object.entries(INTENTS).map(([k, v]) => [k, e(v.desc), `×${v.xi.toFixed(2)}`, v.complexity]))}`;
}

function pageConversions() {
  return `<p>Conversion nodes are where the risk lives. One node choice, and the caster has decided whether to be careful or quick.</p>
    ${table(["Name", "Description", "Œ modifier", "Complexity factor", "Tier"],
      Object.entries(CONVERSIONS).map(([k, v]) => [k, e(v.desc), `×${v.orie}`, `×${v.complexityFactor}`, "I"]))}`;
}

function pageShapes() {
  const forms = TIERS.map(t => {
    const rows = Object.entries(FORMS).filter(([, f]) => f.tier === t.tier)
      .map(([k, f]) => [`<strong>${k}</strong>`, e(f.desc), f.complexity, `×${f.xi.toFixed(2)}`, e(f.notes)]);
    return rows.length ? `<h4>Tier ${t.numeral} Forms</h4>${table(["Shape", "Description", "Complexity", "ξ ×", "Notes"], rows)}` : "";
  }).join("");
  return `${forms}
    <h3>Range</h3>
    ${table(["Tier", "Descriptor", "Effective distance", "ξ range mod", "Description"],
      Object.entries(RANGES).map(([k, r]) => [TIERS[k - 1].numeral, r.label, `${r.distance} (${r.metres})`, `×${r.xi.toFixed(2)}`, e(r.desc)]))}
    <h3>Size</h3>
    ${table(["Tier", "Descriptor", "Area / volume", "ξ multiplier", "Description"],
      Object.entries(SIZES).map(([k, s]) => [TIERS[k - 1].numeral, s.label, `${s.area} (${s.metres})`, `×${s.xi.toFixed(2)}`, e(s.desc)]))}
    <p><strong>Shape Total Mod = ξ<sub>range</sub> × ξ<sub>shape</sub> × ξ<sub>size</sub></strong></p>`;
}

function pageEffects() {
  return `<p>An Effect node does the work. The Elemental effect takes a damage type; the others are named.</p>
    ${table(["Category", "Effect", "Description", "Intent", "Complexity"],
      Object.entries(EFFECTS).filter(([, v]) => !v.custom).map(([k, v]) => [v.category, `<strong>${k}</strong>`, e(v.desc), v.intents.join(" / "), v.complexity]))}
    ${Object.values(EFFECTS).some(v => v.custom) ? `
    <h3>This table's own Effect nodes</h3>
    <p>Effect node items in the world and its compendiums. Not part of the catalogue.</p>
    ${table(["Category", "Effect", "Description", "Intent", "Complexity", "At Might", "Where"],
      Object.entries(EFFECTS).filter(([, v]) => v.custom).map(([k, v]) =>
        [e(v.category), `<strong>${e(v.label ?? k)}</strong>`, e(v.desc), v.intents.join(" / "), v.complexity, e(v.template), e(v.source ?? "")]))}` : ""}
    <p>A compound damage type (Ghost Flame, Rotting Sickness, Radiant Lightning, Divine Flame, Cutting Force) adds +${COMPOUND_COMPLEXITY_BONUS} complexity — a house ruling.</p>
    <h3>Disciplines</h3>
    ${table(["Discipline", "Core function", "Melfyric behaviour", "Risk profile"],
      Object.entries(DISCIPLINES).map(([k, d]) => [`<strong>${k}</strong>`, e(d.core), e(d.behaviour), e(d.risk)]))}`;
}

/* What each node does when the spell is cast. HOUSE RULES: the catalogue
   gives one line per node; these are the table procedures built on it. */
const AT_THE_TABLE = {
  "Split":     "One branch per split, plus the first: target a token for each. Each branch carries Might ÷ branches and is rolled on its own.",
  "Combiner":  "The Effect nodes stop sharing the Might: each carries all of it.",
  "Delay":     "Nothing happens at the cast. The effects release 3 s × count later, on the game clock.",
  "Gate":      "Primed, not released: it waits in the rail until the caster triggers it, fading (e^−kt) while it waits.",
  "Sync":      "The damage effects land as one roll, at one hit location: armour counts once.",
  "Amplifier": "More ξ, and so more Might (Might = ξ).",
  "Anchor":    "A lasting spell holds a place, not a person. Damage taken inside it can be marked in the damage dialog.",
  "Orbit":     "A lasting spell circles its target and strikes it again every Melee Round it lasts.",
  "Link":      "A lasting Shield or Barrier becomes one pool shared by count + 1 allies (the tokens targeted).",
  "Field":     "Everyone within the spell's Size radius, around the one target or the caster.",
  "Mirror":    "A second chain of the same effects at half Might, rolled separately.",
  "Collapse":  "When it ends, anything still pending goes off at once, and a standing structure bursts for Force damage from the ξ it still holds.",
  "Echo":      "The effects repeat one Melee Round later at half Might.",
  "Adaptive":  "More ξ, by its level: set the level to the place (×1.2 calm, ×1.8 resonant)."
};

function pageUtility() {
  return `<p>Flow control. Each adds complexity (ΔC) and multiplies ξ (Mξ), and with it Might, since Might = ξ. Where ΔC is "per" something, it scales with the count; the ξ multiplier applies once per node.</p>
    ${table(["Node", "Function", "ΔC", "Mξ", "At the table"],
      Object.entries(UTILITY_NODES).map(([k, u]) => [`<strong>${k}</strong>`, e(u.desc),
        u.per ? `+${u.dc} per ${u.per}` : `+${u.dc}`,
        u.levels ? `×${u.levels[0]}–×${u.levels[u.levels.length - 1]}` : `×${u.xi}`,
        e(AT_THE_TABLE[k] ?? "")]))}
    <p>Damage on a spell's card has an <strong>Apply</strong> button: it goes through the target's Shields and Barriers, then armour, then a hit location.</p>
    <p class="mm-hint">House rules: the Node Catalogue gives each node a one-line function and its costs; "At the table" is how they are played here.</p>`;
}

function pageDamage() {
  return `<h3>Attack Spells</h3>
    <p>An Attack Intent spell must include one Effect Node capable of dealing direct or indirect damage.</p>
    <p>Valid examples: Fire (Thermal) burns the target; Lightning (Electrical) shocks and stuns; Force (Kinetic) blunt impact; Acid (Chemical) corrodes over time; Wind (Kinetic) knocks back or slashes at high velocity.</p>
    <p>Invalid on their own: Light (non-radiant use), Illusion, Link, Resonance — unless modified by a damage-capable node.</p>
    <h3>Damage Types</h3>
    ${table(["Name", "Description", "Effects"],
      Object.entries(DAMAGE_TYPES).map(([k, d]) => [`<strong>${k}</strong>${d.compound ? `<br><em>${d.compound.join(" + ")}</em>` : ""}`, e(d.desc), e(d.effects)]))}`;
}

function pageTiers() {
  return `<p>A spell's tier is read off its total ξ.</p>
    ${table(["Tier", "Arcane name", "ξ range", "Flavour"],
      TIERS.map(t => [t.numeral, `<strong>${t.name}</strong>`, t.max === Infinity ? `${t.min}+` : `${t.min}–${t.max}`, e(t.desc)]))}`;
}

function pageCasting() {
  const grade = (k) => DIFFICULTY_GRADES.find(g => g.key === k)?.label ?? k;
  return `<p class="mm-hint"><em>The Spell Builder document stops at the formulas; this is how Dreoarcana puts them on the Mythras table. Rolls, grades and Magic Point costs follow the Mythras rulebook (page numbers below are the 3rd printing); tier difficulty and Heat are house rules.</em></p>
    <ol>
      <li><strong>Choose how you cast.</strong> On the Caster node in the Arcanum: skill, Focus, catalyst, how much Stored Orie to draw (all the spell needs, unless you say less), and the circumstances. The status bar shows the target, Orie, Heat and casting time as you change them.</li>
      <li><strong>Roll d100</strong> against the skill at the tier's difficulty grade (house rule), using the Mythras grade multipliers (p.38):
        ${table(["Tier", "Grade"], TIERS.map(t => [`${t.numeral} ${t.name}`, grade(TIER_DIFFICULTY[t.tier])]))}
        Circumstances move that grade (p.38, p.120). Each casting requirement denied (clear thought, a free hand, a voice, perception of the target) makes it one grade harder; a minute of preparation makes it one grade easier and an hour two (p.115). Past Herculean the attempt is Hopeless.
        ${table(["Circumstance", "Grades"], CIRCUMSTANCES.map(c => [e(c.label), c.steps > 0 ? `+${c.steps}` : String(c.steps)]))}
        As for any skill (p.37): 01–05 always succeeds and 96–00 always fails; 99–00 fumbles (only 00 above 100%); a critical is a roll of one tenth of the graded skill or less, rounded up.</li>
      <li><strong>Pay.</strong> The Orie drawn is deducted from Stored Orie in whole points, by result, as Mythras Folk Magic charges Magic Points (p.122): nothing on a critical, the points on a success or failure, and 1d3 more on a fumble. Whatever Stored Orie didn't cover (Œ_final − drawn) is converted on the spot: it costs no pool, but it makes the Heat.</li>
      <li><strong>Heat</strong> is added to the caster, scaled by the outcome:
        ${table(["Outcome", "Stored Orie", "Heat", "Effect", "Note"], Object.values(OUTCOMES).map(o => [o.label, o.orie ? (o.extraOrie ? `drawn + ${o.extraOrie}` : "drawn") : "none", `×${o.heat}`, o.effect ? "manifests" : "none", e(o.note)]))}</li>
      <li><strong>While casting</strong> (p.120) the caster may only walk and take Free or Reactive Actions. A Minor Wound calls for Willpower or the casting is one grade harder; a Serious Wound makes it one grade harder on a passed Willpower and two on a failure; a Major Wound or mental domination fails it outright. A Serious Wound also stops the victim starting a spell for 1d3 Turns (p.110).</li>
      <li><strong>Damage.</strong> Might is turned into dice averaging M ÷ ${setting(SETTINGS.xiPerDamage) ?? 2} (setting), whole d6s first, remainder flat. Rolled on the card for each damage-capable effect.</li>
    </ol>
    <h3>Focus presets</h3>
    ${table(["F", "Circumstance"], Object.entries(FOCUS_PRESETS).map(([v, l]) => [v, e(l)]))}
    <h3>Catalyst presets</h3>
    ${table(["Γ", "Catalyst"], Object.entries(CATALYST_PRESETS).map(([v, l]) => [v, e(l)]))}
    <p>Any piece of gear can be flagged as a catalyst from its item sheet, with its own Γ and Worth; carried catalysts appear first on the Caster node.</p>`;
}

function pageLasting() {
  const k = setting(SETTINGS.decayRate) ?? 0.2;
  const toHeat = setting(SETTINGS.barrierHeat) !== false;
  return `
    <p>From <em>Mechanical Casting</em>, "Spell Persistence & Decay". Every spell that outlasts its casting is one of these; choose it on the bench, under Might.</p>
    <ul>
      <li><strong>Self-sustaining</strong>: "You build it, and the world carries it." Heat is paid once, at casting. Its ξ then fades: <strong>ξ(t) = ξ₀ × e^(−kt)</strong>, with t in Melee Rounds and k = ${k}. It has faded when ξ falls below 1. Shields and Barriers weaken with it.</li>
      <li><strong>Maintained</strong>: "You keep the wound open by will alone." Its ξ holds, but <strong>Heat_maintained = Heat_base × rounds</strong>: the spell's full Heat (nothing drawn from Stored Orie) comes again every Melee Round. It ends when the caster lets go, or collapses when the Heat overflows capacity.</li>
      <li><strong>Transitional</strong>: maintained until released, then self-sustaining from the ξ it had.</li>
    </ul>
    <p>A lasting Defensive or Support spell goes on the one token you target when you cast; otherwise on the caster. Held spells show in the Arcanum's rail and on the character sheet, where the caster can let them go. Game time drives them: each Melee Round of combat, or time advanced by the GM.</p>
    <h3>Shields and Barriers</h3>
    <ul>
      <li><strong>Shield</strong>: a pool of temporary HP equal to its Might. Physical damage hits it first; when it reaches zero, the shield breaks. Some effects bypass it.</li>
      <li><strong>Barrier</strong>: stops Might × 2% of magical damage (5–90%)${toHeat ? ", and what it stops becomes the caster's Heat; past capacity the Barrier collapses" : ""}. It is permeable to martial fighters.</li>
    </ul>
    <p>Mythras damage is applied by hand, so use <strong>Damage</strong> (Arcanum rail) or <strong>Take damage</strong> (character sheet): Shields and Barriers act first, then armour, then a hit location you choose or roll.</p>
    <p class="mm-hint">House rules, both settings: t is counted in Melee Rounds (the canon gives no unit), and the two Barrier texts are read together, percentage and Heat.</p>`;
}

function pageHeat() {
  return `<p class="mm-hint"><em>House procedure, from two sentences of design intent: Heat "has to be dissipated or it can cause permanent damage to a wielder", and reservoirs let casters "build up Melfyrium for use in battle without creating heat".</em></p>
    <h3>Heat</h3>
    <ul>
      <li><strong>Capacity</strong> = CON × ${setting(SETTINGS.heatCapacityPerCon) ?? 3}.</li>
      <li>Past capacity, every <strong>${setting(SETTINGS.heatPerWound) ?? 5}</strong> points of Heat burn one hit point off a random hit location, ignoring armour. The burn is inside.</li>
      <li><strong>Venting</strong>: ${setting(SETTINGS.ventPerRound) ?? 2} Heat per Melee Round of doing nothing else. Each wearable radiator the caster carries adds its metal's conductance ÷ 100 (silver and copper 4, gold 3, aluminium 2; a house rule built from the Materials table). The Vent control in the Arcanum applies it; the GM can cool a caster completely. Heat is shown in the character sheet's header and under Attributes on the main tab, where its capacity takes a modifier.</li>
    </ul>
    <h3>Stored Orie (the reservoir)</h3>
    <ul>
      <li><strong>Capacity</strong> is the character's Stored Orie maximum (POW, plus any modifier on the sheet).</li>
      <li><strong>Filling it</strong> is building up Melfyrium out of combat; nothing is converted, so there is no Heat. It recovers as Mythras Magic Points do (p.117): only with complete rest, comfort and freedom from threat, at the campaign's rate — 1 per hour (magic rich), 1 per day (medium) or 1 per week (low).</li>
      <li><strong>Ongoing magic</strong> (p.120): Orie spent on a spell that is still active cannot start to recover until that spell is dismissed or expires.</li>
      <li><strong>Casting from it</strong> subtracts the drawn Orie from Œ_final before conversion, so that part makes no Heat.</li>
      <li><strong>Running dry.</strong> Mythras stops casting at zero Magic Points by default (p.117). Dreoarcana does not: a caster with no Stored Orie still casts, converting every point of Œ on the spot and eating all the Heat. An empty reservoir isn't a wall; it's a burn.</li>
    </ul>
    <p>Stored ξ produces no Heat, since no conversion is happening.</p>`;
}

export function rulesPages() {
  return [
    { name: "1. The Five Formulas", html: pageFormulas() },
    { name: "2. Intent Nodes", html: pageIntents() },
    { name: "3. Conversion Nodes", html: pageConversions() },
    { name: "4. Shape Nodes", html: pageShapes() },
    { name: "5. Effect Nodes", html: pageEffects() },
    { name: "6. Utility Nodes", html: pageUtility() },
    { name: "7. Damage Types and Attack Spells", html: pageDamage() },
    { name: "8. Power Tiers", html: pageTiers() },
    { name: "9. Casting (house procedure)", html: pageCasting() },
    { name: "10. Heat and Reservoirs (house procedure)", html: pageHeat() },
    { name: "11. Lasting Spells, Shields and Barriers", html: pageLasting() }
  ];
}

export function findRulesJournal() {
  return game.journal?.find(j => j.flags?.[SYSTEM_ID]?.arcanaRules)
      ?? game.journal?.getName(RULES_TITLE)
      ?? null;
}

export async function buildRulesJournal({ notify = true } = {}) {
  const pages = rulesPages().map((p, i) => ({
    name: p.name, type: "text",
    title: { show: true, level: 1 },
    text: { format: 1, content: p.html },
    sort: (i + 1) * 100,
    ownership: { default: -1 }
  }));

  let journal = findRulesJournal();
  if (journal) {
    // Update in place, by page name, so page ids — and any links to them —
    // survive. Only pages whose text actually changed are written.
    const byName = new Map(journal.pages.map(p => [p.name, p]));
    const updates = [], creates = [];
    for (const page of pages) {
      const hit = byName.get(page.name);
      if (!hit) creates.push(page);
      else if (hit.text?.content !== page.text.content || hit.sort !== page.sort) updates.push({ _id: hit.id, "text.content": page.text.content, sort: page.sort });
      byName.delete(page.name);
    }
    const stale = [...byName.values()].map(p => p.id);
    if (updates.length) await journal.updateEmbeddedDocuments("JournalEntryPage", updates);
    if (creates.length) await journal.createEmbeddedDocuments("JournalEntryPage", creates);
    if (stale.length) await journal.deleteEmbeddedDocuments("JournalEntryPage", stale);
    if (notify) ui.notifications.info(`${RULES_TITLE}: ${updates.length + creates.length ? "rules refreshed" : "already up to date"}.`);
    return journal;
  }

  const folder = game.folders.find(f => f.name === FOLDER && f.type === "JournalEntry")
              ?? await Folder.create({ name: FOLDER, type: "JournalEntry", color: "#4a3c8c" });

  journal = await JournalEntry.create({
    name: RULES_TITLE, folder: folder.id, pages,
    ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER },
    flags: { [SYSTEM_ID]: { arcanaRules: true } }
  });
  if (notify) ui.notifications.info(`${RULES_TITLE}: created with ${pages.length} sections.`);
  return journal;
}
